name: 'Block Merge if Non Backwards Compatible Changes'

on:
  pull_request_target:
    types: [labeled, unlabeled]

jobs:
  do-not-merge:
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: If label exists
        if: ${{ contains(github.event.*.labels.*.name, 'non-backwards-compatible-changes') }}
        run: |
          echo "Pull request is labeled as 'non-backwards-compatible-changes'"
          echo "Address the comments regarding the possible non backwards compatible changes and delete the label when done."
          exit 1
      - name: If label does not exist
        if: ${{ !contains(github.event.*.labels.*.name, 'non-backwards-compatible-changes') }}
        run: |
          echo ${{ github.event.*.labels.*.name }}
          echo "Pull request is NOT labeled as 'non-backwards-compatible-changes'"
          exit 0
