name: 'Block Merge if Non Backwards Compatible Changes'

on:
  pull_request_target:
    types: [labeled, unlabeled]

jobs:
  do-not-merge:
    if: ${{ contains(github.event.*.labels.*.name, 'non-backwards-compatible-changes') }}
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "Pull request is labeled as 'non-backwards-compatible-changes'"
          echo "Address the comments regarding the possible non backwards compatible changes and delete the label when done."
          exit 1
  do-merge:
    if: ${{ !contains(github.event.*.labels.*.name, 'non-backwards-compatible-changes') }}
    name: Can Merge
    runs-on: ubuntu-latest
    steps:
      - name: Label not found
        run: |
          echo "Pull request is not labeled as 'non-backwards-compatible-changes'"
          exit 0
